<?php

class CompteCourant extends BankAccount
{
    private bool $decouvertAutoriser;
    private float $decouvertMax;

    /**
     * @param bool $decouvertAutoriser
     * @param float $decouvertMax
     */
    public function __construct(
        bool $decouvertAutoriser,
        float $decouvertMax,
        string $accountNumber,
        float $balance,
        User $user
    ) {
        parent::__construct($accountNumber, $balance, $user);
        $this->decouvertAutoriser = $decouvertAutoriser;
        $this->decouvertMax = $decouvertMax;
    }


    public function isDecouvertAutoriser(): bool
    {
        return $this->decouvertAutoriser;
    }

    public function setDecouvertAutoriser(bool $decouvertAutoriser): void
    {
        $this->decouvertAutoriser = $decouvertAutoriser;
    }

    public function getDecouvertMax(): float
    {
        return $this->decouvertMax;
    }

    public function setDecouvertMax(float $decouvertMax): void
    {
        $this->decouvertMax = $decouvertMax;
    }

    public function withDraw(float $ammount)
    {
        parent::withDraw($ammount); // TODO: Change the autogenerated stub
    }

    public function  getFrais(): float
    {
        $this->withDraw(BankAccount::$cost);
        return BankAccount::$cost;
    }
}
